### ISSUE TITLE
Is it possible for indented comments to be processed?

### ISSUE THREAD

**Issue by jcowgar** [jdtsmith/outli#10]
I program in Elixir and use the common formatter. Code starts (typically) with a module definition (single line) and then everything is indented from there. For example:

```elixir
defmodule Greeter.Hello do
  ### Front matter

  alias Abc.Xyz
  alias Xyz.Abc

  ### Public Interface

  def greet(who) do
    "#{greeting()}, #{who}"
  end

  ### Private functions

  def greeting do
    "Hello"
  end
end
```

I really like Outli in elisp. Can it be used in a language as above?

**Comment by jdtsmith** [comment]
In fact I had a branch named `indented-headlines` that allows this.  Can you give it a try and let me know if things work well?

**Comment by jcowgar** [comment]
Works beautifully! Thank you for the pointer to that branch, I didn't see it until you pointed it out.

**Comment by jdtsmith** [comment]
Great.  I had developed it locally but never pushed it.  I'll merge this in, probably with the option turned off by default.
