### ISSUE TITLE
Separete consult source for outli

### ISSUE THREAD

**Issue by leafarbelm** [jdtsmith/outli#11]
When using `(setq use-package-enable-imenu-support t)` with `outli-mode` packages and headings appear in the same consult source in `consult-imenu`:

![image](https://github.com/jdtsmith/outli/assets/71148349/50458a6a-be16-44b9-83b6-8b47300c02d0)

Its possible to create a separated source for headings?

**Comment by jdtsmith** [comment]
Here's what I do:

```
(push '(?h "Headings")
	(plist-get (cdr (assoc 'emacs-lisp-mode consult-imenu-config)) :types))
```

But you should give `consult-outline` a try!

**Comment by leafarbelm** [comment]
After adding this snippet Its works exactly how i expected, maybe you should add this in the package i think it would be a good addition.

Thanks for the cool package!!
