### ISSUE TITLE
outli and pdf-tools (PDF Outline)

### ISSUE THREAD

**Issue by rdiaz02** [jdtsmith/outli#13]
This is not a bug, but might be worth pointing out in the documentation.

Enabling `outli` when using pdf-tools (https://github.com/vedang/pdf-tools) breaks the bindings (and highlighting) in the PDF Outline (once a pdf is open, `M-x pdf-outline`) . PDF Outline derives from text mode.

Adding hooks to the specific modes (e.g., pdf-outline-buffer-mode) to disable outli (when it had been enabled in text mode) did not seem to restore the original PDF Outline functionality and looks. 

The following, however, works (enable in all text except pdf modes):
 
```elisp
;; Based on  https://emacs.stackexchange.com/a/32418
(defun turn-outli-text-no-pdftools ()
  "Turns on `outli-mode' unless I don't want it."
  (let ((exceptions '(pdf-view-mode pdf-outline-buffer-mode pdf-outline-minor-mode)))
    (unless (apply 'derived-mode-p exceptions)
      (outli-mode 1))))

(use-package outli
   ;; other stuff
   :init ( (add-hook 'text-mode-hook 'turn-outli-text-no-pdftools) )
  ;; other stuff
)
```

Maybe this could be pointed out in the documentation right after "You should probably not enable outli in org-mode (which by default is prevented), or with other packages which operate on headings, like outshine" (https://github.com/jdtsmith/outli#configuration).  It might also help other people who want to not enable outli in other problematic derived modes. I can submit a PR.

**Comment by jdtsmith** [comment]
Interesting, had no idea pdf-tools derived from text-mode (which seems like a strange choice).  An easier way is to add a disable entry to `outli-heading-config`; see the FAQ.  I've added a reminder of that and mentioned pdf-tools.

**Comment by rdiaz02** [comment]
Thanks (I obviously missed it :sweat_smile: ). 

> had no idea pdf-tools derived from text-mode

I am not sure about all of it, but the outline does (I found it disabling outli in text-mode, and then things got back working).
