### ISSUE TITLE
[Requrest for functionality] Export to orgmode file

### ISSUE THREAD

**Issue by bradprob** [jdtsmith/outli#15]
Hi,
First of all thanks for this nice package!
By having an export mechanism to convert ouli comments to an org-mode file we would be able to use the the power of org-mode for generating source code documentation.
I would like to help if the idea is considered as attractive.
Regards

**Comment by jdtsmith** [comment]
Do you just mean copy all of the outline headers into org headings?

**Comment by bradprob** [comment]
Yes, plus extending outli to have content for each heading.

**Comment by jdtsmith** [comment]
That sounds a bit out of scope for outli, which is mostly concerned with outlining and navigation, not content.  Perhaps a separate package?

**Comment by bradprob** [comment]
A new package makes sense, reconsidering the idea, it does not fit outli indeed.
