### ISSUE TITLE
Emacs 31 treesit-outline issue

### ISSUE THREAD

**Issue by QuarterHeaven** [jdtsmith/outli#17]
Hi I'm encountered some error while using outli. I enabled outli in prog-mode, and while in .el or other files (like .vue), revert-buffer works well. But in java files, while I tried to revert-buffer, it reports:

```
outline-map-region: Wrong type argument: number-or-marker-p, nil
```

The Backtrace is like:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  #f(compiled-function () #<bytecode -0x1964e0de811a96ab>)()
  outline-map-region(#f(compiled-function () #<bytecode -0x1964e0de811a96ab>) 1 31382)
  outline--hidden-headings-paths()
  outline-revert-buffer-restore-visibility()
  #f(compiled-function (f) #<bytecode 0x6badcbe8273644b>)(outline-revert-buffer-restore-visibility)
  run-hook-wrapped(#f(compiled-function (f) #<bytecode 0x6badcbe8273644b>) outline-revert-buffer-restore-visibility)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  call-interactively(revert-buffer record nil)
  command-execute(revert-buffer record)
  execute-extended-command(nil "revert-buffer" "rev")
  funcall-interactively(execute-extended-command nil "revert-buffer" "rev")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

The `outline-level`'s value is `#'outli-indent-level`. And in both files, `M-: (outli-indent-level)` reports `nil`.

If I disabled outli, I can successfully revert the buffer. How to solve this?

**Comment by jdtsmith** [comment]
What is `outline-search-function` in this buffer?

**Comment by QuarterHeaven** [comment]
> What is `outline-search-function` in this buffer?

It's `#'treesit-outline-search`. Did they conflict?

**Comment by jdtsmith** [comment]
I think they may be.  What version of emacs?  What happens if you set that variable to `nil`?

**Comment by QuarterHeaven** [comment]
> I think they may be. What version of emacs? What happens if you set that variable to `nil`?

`(emacs-version)`: "GNU Emacs 31.0.50 (build 1, aarch64-apple-darwin24.1.0, NS appkit-2575.20 Version 15.1 (Build 24B83), git sha1 0756b1f2f54) of 2024-11-11"

The buffer can successfully revert when that is `nil`.

**Comment by jdtsmith** [comment]
This seems to be a new conflict with Emacs 31, and potentially a problem with `treesit-outline`.  Can you please file an Emacs bug report and link it here?

**Comment by QuarterHeaven** [comment]
> This seems to be a new conflict with Emacs 31, and potentially a problem with `treesit-outline`. Can you please file an Emacs bug report and link it here?

I've reported it and here is the [link](https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-11/msg00927.html)

**Comment by QuarterHeaven** [comment]
> OK I just find the java-ts-mode and treesit.el is not from `straight'... 
> So the start script now only load `outli'.
> 
> 
> I tried clone `outli' into `~/src/outli', and it works fine, while the 
> straight build version is not.
> 
> 
> I diffed the `~/.emacs.d/straight/build/outli/outli.el' with 
> `~/src/outli/outli.el' and found that they are same. But there is a
> 
> file `outli-autoloads.el' in `~/.emacs.d/straight/build/outli', which be 
> generated by `straight'. This file contains:
> 
> ```elisp
> 
> (autoload 'outli-mode "outli" "\ Simple outline mode interaction based 
> on comment-headings. This is a minor mode. If called interactively, 
> toggle the `Outli mode' mode. If the prefix argument is positive, enable 
> the mode, and if it is zero or negative, disable the mode. If called 
> from Lisp, toggle the mode if ARG is `toggle'. Enable the mode if ARG is 
> nil, omitted, or is a positive number. Disable the mode if ARG is a 
> negative number. To check whether the minor mode is enabled in the 
> current buffer, evaluate the variable `outli-mode'. The mode's hook is 
> called both when the mode is enabled and when it is disabled. 
> \\{outli-mode-map} (fn &optional ARG)" t) (register-definition-prefixes 
> "outli" '("outli-"))
> 
> ```
> 
> I commented the line `(register-definition-prefixes "outli" 
> '("outli-"))', and load `~/.emacs.d/straight/build/outli/outli.el',
> 
> and the `revert-buffer' works.

I just found this issue might be caused by straight...

**Comment by QuarterHeaven** [comment]
OK, it seems I just pulled the latest version with straight but forgot to rebuild… sorry for the bother.
