### ISSUE TITLE
Can't blend an "unspecified" foreground

### ISSUE THREAD

**Issue by DamienCassou** [jdtsmith/outli#2]
When I start Emacs in daemon mode (with `--fg-daemon`), Emacs crashes with this stack trace:

```
(color-rgb-to-hex)
(outli-fontify-background-blend unspecified)
(outli-fontify-headlines t nil)
(outli-mode)
```

At this point, in `outli-fontify-headlines`, `ol-face` is `org-level-8` and `fg` is `unspecified`.

**Comment by jdtsmith** [comment]
Strange that it has no foreground; perhaps it's a load order issue.  I just pushed a commit which puts up a stronger defense against unspecified fg/bg colors.  Let me know if that fixed it.

**Comment by DamienCassou** [comment]
I don't see any commit or any branch. Can you please double-check?

**Comment by jdtsmith** [comment]
Sorry unresolved conflict; should be there now.

**Comment by DamienCassou** [comment]
The fix works for me, thank you very much. Feel free to close the issue.
